### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by Bopon0409** [connext/community-sybil-reports#230]
Accounts:
0xaec19d15f1b6b737c8f374fd90d1f19ca8fcbdeb
0x6c209c19deea3809aa4cd3dc2039e9af73d4fd44
0xc96b54890f172986f8edc7aec6e8c09a53760526
0xc726a77353dbc81fc506d71fa6752b8a44b4736d
0x64e1a38cbdcec7753e1242f0a23f6a6d6c9f4fa3
0x673176bdf8431153dcfdbeb69afe3308e23dc4ed
0x4265fb52e31b1eab0193f36e9c3480deca79f9c6
0xf9be154c91bbfc898b1e683aca683973d7c525ef
0xd8abbb00661c9db59f22eeda7950d4cbb3eedb57
0x3b2f8c00cc8593d9cbd1ca644c44203e817e2c71
0x542e4dc1d3e7314ccbe93568baa428b01eb90fbc
0x8c9d6173cd7a77dd71e1a4e67c5cfeda424e6242

Networks I have considered: Polygon | Gnosis Chain.

### Methodology
How I found these accounts:
Running my script on Gnosis Chain, I decided to observe the gas limit set for identical values. I noticed that the gas limit was 662352 for 12 transactions.

### Reasoning
I examined all transactions on the Gnosis Chain network involving these wallets, and here's what I found interesting:
On February 25, 2023, using the contract 0x29b6603d17b9d8f021ecb8845b6fd06e1adf89de, all 12 wallets were funded with amounts ranging from 895 to 900 USDC (one wallet was funded with 950 USDC). The wallet balances differed by just a few tens of cents. Thus, the wallets couldn't be distinguished based on the amounts. Interaction with this contract occurred on almost all accounts from Feb-25-2023 12:39:45 PM to Feb-25-2023 03:56:10 PM +UTC. All accounts began interacting with Connext only after Feb-25-2023 03:00:00 PM +UTC. This suggests that the wallet owner aimed to diversify the timing of account actions and funded the accounts over several hours.

Subsequently, all 12 accounts exchanged all USDC tokens for nextUSDC and added liquidity to the pool (addSwapLiquidity).
Upon closer inspection of the transactions, I discovered that all these transactions involved exchanging around 895-900 USD worth of nextUSDC for CUSDCLP (only one account, 0xae...bdeb, exchanged 950 nextUSDC). Looking at the transaction execution dates, I noticed that all 12 wallets made this exchange within a span of 70 minutes, using the aforementioned gas limit of 662352. This was the initial link connecting these accounts.

The next set of actions with Connext began only on Mar-18-2023, involving 9 accounts (0x64e1a38cbdcec7753e1242f0a23f6a6d6c9f4fa3, 0x3b2f8c00cc8593d9cbd1ca644c44203e817e2c71, 0xd8abbb00661c9db59f22eeda7950d4cbb3eedb57, 0x4265fb52e31b1eab0193f36e9c3480deca79f9c6, 0xf9be154c91bbfc898b1e683aca683973d7c525ef, 0xc96b54890f172986f8edc7aec6e8c09a53760526, 0x6c209c19deea3809aa4cd3dc2039e9af73d4fd44, 0xaec19d15f1b6b737c8f374fd90d1f19ca8fcbdeb, 0xc726a77353dbc81fc506d71fa6752b8a44b4736d). Throughout the day, these accounts executed similar actions with varying amounts, following this sequence: swap - swap - swap - swap - swap - swap - xcall. The xcall function was executed on all 9 accounts on Mar-21-2023, three days after the swaps.

Further examination reveals similar patterns of actions among the accounts.
All accounts withdrew funds from the Gnosis Chain network using xcall Connext on May-23-2023 06:49:05 AM +UTC, over a span of 3 hours. Some wallets performed this withdrawal in a single transaction, while others used two.

Following these events, many of the accounts were funded with OKX on the Polygon network on the same day, and liquidity was added (addSwapLiquidity).

I thoroughly analyzed the interactions on Gnosis Chain with Connext. However, it could have been insightful to examine Polygon as well, where I observed similar repetitive transactions. There, the primary deposits/withdrawals or other financial activities occur on a single day within a span of a few hours, mirroring the patterns I observed on Gnosis Chain.

As another example, I can mention the minting of mint NFTs by Galxe (Proto-Being (#AntiSybilAssembly), Earthling (#AntiSybilAssembly), Egg (#AntiSybilAssembly), Awakened Being (#AntiSybilAssembly), and minting NFTs using the contract 0x8419f704cd6520e2c3ef477ef9bfa3159ea1aca7 - half walletsl) (Aug-01-2023 11:05 AM +UTC). Within a span of 70-80 minutes, all these actions were repeated by all accounts.

These accounts exhibit a significant number of identical actions, occurring at intervals of 10-20 minutes between accounts. While there are other transactions as well that aim to diversify the activity among the accounts. However, with 90% confidence, I can assert that these accounts are controlled by a single individual/company.

It's actually easier to take a look for yourselves to see with your own eyes :)

==================================================
### Rewards Address: 
0x5EC747B11C14eaeA27656b897072451d5A0D82DB

**Comment by preethamr** [comment]
This does look like, these addresses are owned by the same entity. Based on graph analysis.
I lean towards valid, further review required.

**Comment by Vladislav1z** [comment]
@preethamr To my great regret, I've just seen this Sybil Report. I'll do my best to explain how everything works. In this list of wallets, there are three addresses that belong to me, while all the other addresses belong to my acquaintances. How is it possible that our activities appear similar? We collaborate within a private Telegram channel, where we discuss and analyze numerous projects. After thorough discussions, we make decisions about engaging in various projects. Our actions might resemble each other's, raising the question: Isn't the crypto community designed for collectively addressing challenges?

Our goal was to reach the top 30 participants providing liquidity. It was no easy task. Personally, I wasn't able to gather many unique NFTs, but some of my acquaintances succeeded – they collected around 3 NFTs per wallet. If you examine the addresses provided above in detail, you'll notice they are unique, despite the similar activities. For instance, we have a dedicated HOPR project enthusiast in our group. They participate in all project activities, have purchased a significant amount of HOPR tokens, run nodes, participate in voting, and more. This individual consistently encourages us to buy project tokens, but most of our team members disagree and believe the token is already obsolete.

I've shared this story to illustrate that we are all distinct active users, each with our own opinions and engagements in the crypto world. Currently, you're asserting that all these wallets belong to one person, but that's not the case. I understand you've already made a decision in favor of considering these addresses as Sybil, but my intention is not to convince you otherwise – just to clarify how it truly unfolded.

**Comment by A-Keyboard** [comment]
@Bopon0409 Can you dm me on Discord, my discord is khlilo

**Comment by Bopon0409** [comment]
> @Bopon0409 Can you dm me on Discord, my discord is khlilo

X465F
