### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by tonixbt** [connext/community-sybil-reports#275]
# Sybil Submission 1
# Related Addresses
0x86fe0e50e37e058e6bd28aad3b1ba94d8149df8b
0x7eeb350b061a75ce81527b10999829b02413c204
0x044a9a297bf92afa0929c128a40963849e20dffa
0x213ec5b6104ea69d29e5cd3c2fb09ceab0279d72
0x79255f1e39e3d603b5ddcf5e4a3bdc77f093c8b3
0xc1657916a9225df4aef89c08ecb9d5c15e567e99
0x43d83c16ec9f154c4d9890e86791227ddc11776c
0xab59a8549608a0b9e3677268312eacc0ca44e660
0xbd77bb2ba02c3f73734ba04107c12499f6b1befd
0x9a43bf16c50a9943b5858c741a531209f1667689
0xaf738f6c83d7d2c46723b727ce794f9c79cc47e6
0xd761856d918dc7f6b2767c4b51be74e1b82cfde8

# Reasoning
Every address listed above has sent their remaining ETH to 0x3986187fa06d5f1b12a49027d346465f79dfa24c on both Ethereum and Arbitrum 49 days ago

Most listed addresses also have a 6-digit ENS domain and have recently interacted with Maverick protocol on Ethereum

# Methodology
Looked through transactions on Connext and found these wallets

# Sybil Submission 2
# Related Addresses
0x5bb427efb60add2d87d16be6a8d5b445789d9697
0x18ad6cbf402fc545ed21512ba744aa2df8f3049e
0xd70ba4fa1d21f283a453f29accccd268771f963a
0x952364a92a7ef4d26015adafd3b0e299c7000b1d
0xd64496b7a390a33eaa8c8046b6989394d39a1a86
0x774fba072cfc0950b5fde157e70835aeb7a48c5c
0xcde55bb3b897028d795a48e42d0a5e9135b818b8
0x18a012312b170f9d40036e0b1d3b6c01d75c1a9a
0x0eb786ec8fa4b13d34bf195a0bd07e11d455dbac
0x0f35a5e5adf879d1ab74760d0d0e7eef294babcf
0x51a42967cd0d603ea459cfb2ab9c93e4b08874bc
0x1d051ccb0104ba547d6ab20079d930f3daaa22bf
0x205bdf8355502dde36a51967c8768ac09bf6d3e5
0x2c5b447be1efeafb1cfac738d3f75c6042d80601
0x36d2472c03b6b6062d39bb3c1e6ae94625197009
0xa9e2ff34265bc5f1cd33ac1e314d5d9c0a37f3b9
0x89b1578f6c6bf68070fdbd27331a38d5780ac574
0xefa374917321169a23aee6a4de70ae9a1e177c1f
0x48e797018bd1e1bf76cf3875785f8fa146a07f7e
0x480daa4805b4fc7de406cb17d508890f8d30f000
0x70427e1277054509f7b677a9199de07d4af2f0e6
0xb6776ba86c0dd77353c405524b5a9609e200849c
0xbbd97ddf3f815e35a5d7f648a346a6a35e6d710a
0x1bcdda10ffa18f10d014fdc564934664f06d8946
0x5002e3b74e7c497a4d33b19c36a1713b6948c186
0x9567e996e65fd95352db2b53d7bca3fc5b52eec7
0x94643ea3e96351de165fb54f21d632bd9d07097e
0xc5985732b131bc7cc82159f689b241c31d203d6d
0xea7c141d6ff1a9c33a104ae4dd28ed3eaa1ca33a
0x76576ed42b5d5bd6fbf7c7bbaeb01d26aa75a5ff
0x1e3bad99d674a684da15f26737728bdda56f231a
0x02e318de112c1e448ae900ee4717ec9ba81be819
0x17ce2bd44fb1ea0ffebf511fb96c4ec5c641790a
0x8b51c31a2ddd471dee5bce28990247d64e232088
0x574cadf03f448d22aa1ba91da9f50c33eabdc542
0xf35899b8514c4b08819f01fa66c4755363dec7e2
0xbe3f0990a129103d0394e855c50ed8b15ec6357a
0xaffc576caf0e3648a59468db6831fc18fabc87e3
0xc8af190c7fafea299a89e6639b417b1426c371c1
0xfa5a0be229e39c3a21e96ecc7f013d27dd461615
0x24cbf32bc77ca9847b523341807f1c9e34d54e1d
0xea29cee16f6f4984f435483717581d1a72995848
0x5deb7670fb178136c6af7f3a06fb56ae30006a3e
0x9d87569e95128b32a93f7a2d8fc7ee60b9063a82
0x039a7bd9add1a5c82f657a0eec3d65b530aff2e7
0xfa64e763c1b485ea2d07c6d3db5f12f608e8907f
0x6bdc4a56d6609e329056b7a26750c47cebfc32be
0xd73206e949ec8729a930201cf74d2f21f0b54034
0x96d796cc3aee8394f9b74e68c40a65805a54cf2f
0x41ec7aaaaaa1f90d4c0f1494baa4a214f60ab194
0xda4289a1026638bf7163984511d3e8d7146dccce
0x59b96a31838974c30babad5202a91690b652d185
0x6af54ca831f947125620dbc1c53aa2fbadb986e3
0xd9f0bed0991485ec3193245c75b60d14a9629f70
0x14770b57bf0d6c49300bb9486846510d7efcb016
0x21c12b59acac71d0e153ea55f5af807eab9c3a65
0x4bfa90eb7cd0a9bb3bcf4ccab6892f351129f562
0x450cc7e4b3ba2f395ebf5b28b2de30da8ef96b7a
0xccef4713a5637a7ed8a616e2abd29a2482934b23
0x562dc67ab94331934af661108016ef1f96783cce
0x07a0e9317fc2c2d44aa9dc6b8c95ece8a7d2a769
0x7b1e21a8c0dea9ec07d689f9477c25ae95160a09
0x775542e4a4a3bcd79b5689ffcc2f5a7d32d5d4d3
0xb373ec17a42dce224ce515b3ef9e6e305f642cee
0x2441b3754dedbbaf59e35162f5bc16645230520a
0x0041bbf0251652ab534e67da80ebe3f928ead570
0x9b2c4f915bd29d03847a3a80da2b05068f3ce284
0x6249a223cdd8e8811d2cd7a709e35549a5fe0481
0x13de345f425c2f0cab1378bd45309b264be9066c
0x4c0e8cab19c294ef7341af980c25c5179edc5e9a

# Reasoning
Every address listed above deposited between 0.04 and 0.09 WETH to Connext on the 9th of February, between 6:30 AM and 2:30 PM

Every address listed above has also used Socket with less than 0.001 ETH either 87 or 95 days ago, confirming their relation

# Methodology
Looked through transactions on Connext and found these wallets which added LP as well as transacted on Socket at the same time

# Sybil Submission 3
# Related Addresses
0x4265fb52e31b1eab0193f36e9c3480deca79f9c6
0x6c209c19deea3809aa4cd3dc2039e9af73d4fd44
0xc726a77353dbc81fc506d71fa6752b8a44b4736d
0xf9be154c91bbfc898b1e683aca683973d7c525ef
0xd8abbb00661c9db59f22eeda7950d4cbb3eedb57
0xaec19d15f1b6b737c8f374fd90d1f19ca8fcbdeb
0xd8b00122b6cc0d44fb3198fb675635272d516b7f
0xc96b54890f172986f8edc7aec6e8c09a53760526
0x8c9d6173cd7a77dd71e1a4e67c5cfeda424e6242
0x673176bdf8431153dcfdbeb69afe3308e23dc4ed
0x64e1a38cbdcec7753e1242f0a23f6a6d6c9f4fa3

# Reasoning
Every address listed above has received 0.001 ETH from 0x0938c63109801ee4243a487ab84dffa2bba4589e on the 17th of November 2022, between 7:30 AM and 4:00 PM

Every address listed above has created a Gnosis Safe using contract 0xa6b71e26c5e0845f74c812102ca7114b6a896ab2

Every address listed above has received between 0.4 and 0.5 ETH from the Orbiter bridge 279 days ago

# Methodology
Looked through transactions on Connext and found similarities between wallets and used said similarities to find all related wallets

# Rewards Address
0xC680FA3BE4437dA0038Aeb10095B71161D43d2FC

**Comment by ArjunBhuptani** [comment]
Clusters 1 and 2 valid

**Comment by Vladislav1z** [comment]
> Clusters 1 and 2 valid


Regarding Cluster 3, I responded in Report #230, but I'll duplicate my answer here once again.
To my great regret, I've just seen this Sybil Report. I'll do my best to explain how everything works. In this list of wallets, there are three addresses that belong to me, while all the other addresses belong to my acquaintances. How is it possible that our activities appear similar? We collaborate within a private Telegram channel, where we discuss and analyze numerous projects. After thorough discussions, we make decisions about engaging in various projects. Our actions might resemble each other's, raising the question: Isn't the crypto community designed for collectively addressing challenges?

Our goal was to reach the top 30 participants providing liquidity. It was no easy task. Personally, I wasn't able to gather many unique NFTs, but some of my acquaintances succeeded – they collected around 3 NFTs per wallet. If you examine the addresses provided above in detail, you'll notice they are unique, despite the similar activities. For instance, we have a dedicated HOPR project enthusiast in our group. They participate in all project activities, have purchased a significant amount of HOPR tokens, run nodes, participate in voting, and more. This individual consistently encourages us to buy project tokens, but most of our team members disagree and believe the token is already obsolete.

I've shared this story to illustrate that we are all distinct active users, each with our own opinions and engagements in the crypto world. Currently, you're asserting that all these wallets belong to one person, but that's not the case. I understand you've already made a decision in favor of considering these addresses as Sybil, but my intention is not to convince you otherwise – just to clarify how it truly unfolded.

**Comment by xuxia305** [comment]
Clusters 1   My stolen address is in it, is it still a witch if it was stolen?

**Comment by xuxia305** [comment]
> Clusters 1 and 2 valid
Clusters 1 My stolen address is in it, is it still a witch if it was stolen?

**Comment by A-Keyboard** [comment]
@tonixbt Can you dm me on Discord, my discord is khlilo

**Comment by tonixbt** [comment]
> @tonixbt Can you dm me on Discord, my discord is khlilo

5643
